FROM ubuntu:18.04
MAINTAINER Wakahiu Njenga <wakahiu.njenga@gmail.com>

# Update the image to the latest packages
RUN apt-get update && apt-get upgrade -y

# Install app dependencies
RUN apt-get install -y python3.7
RUN apt-get install -y python3-pip \
    wget
RUN pip3 install --upgrade pip

# Download and Install Google Chrome and it's dependencies
RUN apt-get install -y gconf-service \
    libasound2 \
    libatk1.0-0 \
    libatk-bridge2.0-0 \
    libc6 \
    libcairo2 \
    libcups2 \
    libdbus-1-3 \
    libexpat1 \
    libfontconfig1 \
    libgcc1 \
    libgconf-2-4 \
    libgdk-pixbuf2.0-0 \
    libglib2.0-0 \
    libgtk-3-0 \
    libnspr4 \
    libpango-1.0-0 \
    libpangocairo-1.0-0 \
    libstdc++6 \
    libx11-6 \
    libx11-xcb1 \
    libxcb1 \
    libxcomposite1 \
    libxcursor1 \
    libxdamage1 \
    libxext6 \
    libxfixes3 \
    libxi6 \
    libxrandr2 \
    libxrender1 \
    libxss1 \
    libxtst6 \
    ca-certificates \
    fonts-liberation \
    libappindicator1 \
    libnss3 \
    lsb-release \
    xdg-utils \
    wget

RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf \
      --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

COPY . /app
WORKDIR "/app"

# Install pip requirements
RUN pip3 install -r requirements.txt

ENV GOOGLE_APPLICATION_CREDENTIALS=./app/proxima-media-a9b18d9e8127.json
ENV REDIS_HOST=10.7.107.171
ENV REDIS_PORT=6379
ENV PYTHONUNBUFFERED=0
ENV PYTHONIOENCODING=utf-8

ENTRYPOINT python3 ./app/main.py
