runtime: python37
entrypoint: python ./app_engine/main.py

vpc_access_connector:
  name: "projects/proxima-media/locations/europe-west1/connectors/proxima-connector"
env_variables:
  REDIS_HOST: "10.7.107.171"
  REDIS_PORT: 6379
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5
